# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=ecommerce.models.image_upload_to),
        ),
    ]
