# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
