# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 15, 53, 29, 781124, tzinfo=utc)),
        ),
    ]
