# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180128_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 13, 3, 26, 235529, tzinfo=utc)),
        ),
    ]
